/**
 * Tier 1 — Revenue-critical: Widget E2E (real API, no mocks)
 *
 * Tests the core product loop end-to-end:
 *   1. Widget loads on an external page bootstrapped with a per-device token
 *   2. Client submits feedback via widget
 *   3. Feedback appears in the dashboard
 *
 * Auth model: the legacy email-prompt flow was removed in slice C2. The widget
 * is now invisible to anonymous visitors and only renders after a per-device
 * token is in localStorage on the host origin. Tests bootstrap that token by
 * navigating to widget-test.html with `?vv_token=<seed.widgetTokens.client>`,
 * which widget.js plants directly into localStorage before stripping the param
 * via `history.replaceState`.
 *
 * Uses the widget-test.html page generated by global-setup with the real API key.
 */

import { test, expect, type Page } from '@playwright/test';
import { getSeedResult } from './utils/seed-result';
import { AUTH_FILES } from './fixtures/test-data';

// Run serially — these tests depend on each other (first creates feedback, second reads it)
test.describe.configure({ mode: 'serial' });

/**
 * Loads the widget test page with a `?vv_token=` bootstrap param so the
 * widget renders on the file:// origin. Returns once the widget's trigger
 * button is visible (proving the bootstrap + config load succeeded).
 */
async function loadWidgetWithToken(page: Page, token: string): Promise<void> {
    const fileUrl = `file://${process.cwd().replace(/\\/g, '/')}/tests/widget-test.html?vv_token=${encodeURIComponent(token)}`;
    await page.goto(fileUrl);

    // Widget host element is mounted synchronously, but its `display` stays
    // `none` until `loadConfig()` resolves on a valid token. Waiting for the
    // trigger button to be *visible* (not merely attached) covers both the
    // mount and the config round-trip in one assertion.
    await expect(page.locator('.trigger-btn')).toBeVisible({ timeout: 15_000 });
}

// ---------------------------------------------------------------------------
// Widget test — uses NO pre-auth session (simulates external visitor)
// ---------------------------------------------------------------------------

test.describe('Widget feedback flow (real API)', () => {
    test.use({ storageState: AUTH_FILES.empty });

    const feedbackContent = `E2E feedback ${Date.now()}`;

    test('client submits feedback via widget → visible in dashboard', async ({ page, context }) => {
        const seed = getSeedResult();

        // ── Step 1: Bootstrap the widget with the seeded client's token ──
        await loadWidgetWithToken(page, seed.widgetTokens.client);

        // ── Step 2: Open the widget ──
        // Playwright pierces Shadow DOM by default
        await page.locator('.trigger-btn').click();
        await expect(page.locator('.popup')).toBeVisible({ timeout: 5_000 });

        // ── Step 3: Submit feedback ──
        // No email prompt anymore — the bearer-token identity is server-authoritative.
        await expect(page.locator('#vv-textarea')).toBeVisible({ timeout: 5_000 });
        await page.locator('#vv-textarea').fill(feedbackContent);
        await page.locator('#vv-submit').click();

        // Success view should appear
        await expect(page.locator('.success-view')).toBeVisible({ timeout: 10_000 });

        // ── Step 4: Verify feedback appears in the dashboard ──
        const dashboardPage = await context.newPage();

        // Load owner auth state
        const fs = require('fs');
        const ownerState = JSON.parse(fs.readFileSync('tests/.auth/owner.json', 'utf-8'));
        await dashboardPage.context().addCookies(ownerState.cookies);

        await dashboardPage.goto('/dashboard/feedback');
        await dashboardPage.waitForLoadState('networkidle');

        // The feedback content should be visible in the list
        await expect(dashboardPage.getByText(feedbackContent)).toBeVisible({ timeout: 15_000 });
    });

    test('widget feedbacks list shows submitted feedback', async ({ page }) => {
        const seed = getSeedResult();

        await loadWidgetWithToken(page, seed.widgetTokens.client);

        // Open widget
        await page.locator('.trigger-btn').click();
        await expect(page.locator('.popup')).toBeVisible({ timeout: 5_000 });

        // Switch directly to the feedbacks tab (no email prompt to clear first)
        await expect(page.locator('#vv-textarea')).toBeVisible({ timeout: 5_000 });
        await page.locator('.nav-item[data-view="feedbacks"]').click();

        // Should see at least one feedback item
        await expect(page.locator('.feedback-item').first()).toBeVisible({ timeout: 10_000 });
    });
});

// ---------------------------------------------------------------------------
// Dashboard feedback interaction — uses owner session
// ---------------------------------------------------------------------------

test.describe('Dashboard feedback interaction', () => {
    test('owner can view feedback detail', async ({ page }) => {
        await page.goto('/dashboard/feedback');
        await page.waitForLoadState('networkidle');

        // Click the first feedback card to open detail view
        const firstCard = page.locator('a[href*="/dashboard/feedback"]').first();
        const hasFeedbacks = await firstCard.isVisible().catch(() => false);
        if (!hasFeedbacks) {
            test.skip(true, 'No feedbacks found — run widget tests first');
            return;
        }

        await firstCard.click();
        await page.waitForLoadState('networkidle');

        // Detail view should show status and content
        await expect(page.getByText('Status')).toBeVisible({ timeout: 10_000 });
    });
});
