/**
 * Tier 1 — Revenue-critical: Widget E2E (real API, no mocks)
 *
 * Tests the core product loop end-to-end:
 *   1. Widget loads on an external page bootstrapped with a per-device token
 *   2. Client places a pin and submits feedback from the composer beside it
 *   3. Feedback appears in the dashboard
 *
 * This is the only test that drives the widget against the real API, real
 * database and real dashboard. `widget-pinning.spec.ts` stubs the endpoints to
 * test anchoring logic, so it cannot catch a server-side break; this one can.
 *
 * Auth model: the legacy email-prompt flow was removed in slice C2. The widget
 * is now invisible to anonymous visitors and only renders after a per-device
 * token is in localStorage on the host origin. Tests bootstrap that token by
 * navigating to widget-test.html with `?vv_token=<seed.widgetTokens.client>`,
 * which widget.js plants directly into localStorage before stripping the param
 * via `history.replaceState`.
 *
 * Uses the widget-test.html page generated by global-setup with the real API key.
 */

import { test, expect, type Page } from '@playwright/test';
import { getSeedResult } from './utils/seed-result';
import { AUTH_FILES } from './fixtures/test-data';
import { supabaseAdmin } from './utils/supabase-admin';

// Run serially — these tests depend on each other (first creates feedback, second reads it)
test.describe.configure({ mode: 'serial' });

/**
 * Loads the widget test page with a `?vv_token=` bootstrap param so the
 * widget renders on the file:// origin. Returns once the widget's trigger
 * button is visible (proving the bootstrap + config load succeeded).
 */
async function loadWidgetWithToken(page: Page, token: string): Promise<void> {
    const fileUrl = `file://${process.cwd().replace(/\\/g, '/')}/tests/widget-test.html?vv_token=${encodeURIComponent(token)}`;
    await page.goto(fileUrl);

    // Widget host element is mounted synchronously, but its `display` stays
    // `none` until `loadConfig()` resolves on a valid token. Waiting for the
    // trigger button to be *visible* (not merely attached) covers both the
    // mount and the config round-trip in one assertion.
    await expect(page.locator('.trigger-btn')).toBeVisible({ timeout: 15_000 });
}

// ---------------------------------------------------------------------------
// Widget test — uses NO pre-auth session (simulates external visitor)
// ---------------------------------------------------------------------------

test.describe('Widget feedback flow (real API)', () => {
    test.use({ storageState: AUTH_FILES.empty });

    const feedbackContent = `E2E feedback ${Date.now()}`;

    test('client submits pinned feedback via widget → visible in dashboard', async ({ page, context }) => {
        const seed = getSeedResult();

        // ── Step 1: Bootstrap the widget with the seeded client's token ──
        await loadWidgetWithToken(page, seed.widgetTokens.client);

        // ── Step 2: Open the widget ──
        // Playwright pierces Shadow DOM by default
        await page.locator('.trigger-btn').click();
        await expect(page.locator('.popup')).toBeVisible({ timeout: 5_000 });

        // ── Step 3: Place a pin, then submit from the composer beside it ──
        // Every widget report is pinned now; the unpinned form is gone.
        await page.locator('#vv-action-pin').click();
        await expect(page.locator('.capture-overlay')).toBeVisible({ timeout: 5_000 });

        // Clicked via page.mouse, not a locator: the placement overlay covers
        // the page on purpose, so a locator click would be reported as
        // intercepted rather than landing on the overlay that reads the point.
        const target = (await page.locator('h1').boundingBox())!;
        await page.mouse.click(Math.round(target.x + target.width / 2), Math.round(target.y + target.height / 2));

        await expect(page.locator('#vv-composer')).toBeVisible({ timeout: 5_000 });
        await page.locator('#vv-composer-text').fill(feedbackContent);
        await page.locator('#vv-composer-submit').click();

        // Success closes the composer; there is no success view any more.
        // Generous timeout: a screenshot may still be uploading behind this.
        await expect(page.locator('#vv-composer')).toBeHidden({ timeout: 20_000 });

        // ── Step 4: Verify feedback appears in the dashboard ──
        const dashboardPage = await context.newPage();

        // Load owner auth state
        const fs = require('fs');
        const ownerState = JSON.parse(fs.readFileSync('tests/.auth/owner.json', 'utf-8'));
        await dashboardPage.context().addCookies(ownerState.cookies);

        await dashboardPage.goto('/dashboard/feedback');
        await dashboardPage.waitForLoadState('networkidle');

        // The feedback content should be visible in the list
        await expect(dashboardPage.getByText(feedbackContent)).toBeVisible({ timeout: 15_000 });
    });

    test('widget feedback list shows submitted feedback', async ({ page }) => {
        const seed = getSeedResult();

        await loadWidgetWithToken(page, seed.widgetTokens.client);

        // Open widget
        await page.locator('.trigger-btn').click();
        await expect(page.locator('.popup')).toBeVisible({ timeout: 5_000 });

        // The list is a toggle on the action bar now, not a tab.
        await page.locator('#vv-action-list').click();

        // Should see at least one feedback item
        await expect(page.locator('.feedback-item').first()).toBeVisible({ timeout: 10_000 });
    });
});

// ---------------------------------------------------------------------------
// Dashboard feedback interaction — uses owner session
// ---------------------------------------------------------------------------

test.describe('Dashboard feedback interaction', () => {
    test('owner can view feedback detail', async ({ page }) => {
        await page.goto('/dashboard/feedback');
        await page.waitForLoadState('networkidle');

        // Click the first feedback card to open detail view
        const firstCard = page.locator('a[href*="/dashboard/feedback"]').first();
        const hasFeedback = await firstCard.isVisible().catch(() => false);
        if (!hasFeedback) {
            test.skip(true, 'No feedback found — run widget tests first');
            return;
        }

        await firstCard.click();
        await page.waitForLoadState('networkidle');

        // Detail view should show status and content
        await expect(page.getByText('Status')).toBeVisible({ timeout: 10_000 });
    });

    test('a pinned reply shows where it was pinned, lettered like the widget', async ({ page }) => {
        // The widget paints a reply pin as "<n>b"; the dashboard cannot know n
        // (numbering is widget-side, project-wide by age) but mirrors the letter
        // so the two can be matched up. Rows are inserted directly: the thread
        // has to exist before the page is opened.
        const seed = getSeedResult();
        const { data: fb, error } = await supabaseAdmin
            .from('feedbacks')
            .insert({
                project_id: seed.projectId,
                content: `E2E reply-pin parent ${Date.now()}`,
                type: 'Bug',
                sender: seed.clientEmail,
                metadata: { page_key: 'https://example.com/' },
            })
            .select('id')
            .single();
        if (error || !fb) throw new Error(`parent insert failed: ${error?.message}`);

        try {
            const anchor = { selector: '#pricing-cta', selectorKind: 'id', offset: { x: { ref: 'pct', d: 0.5 }, y: { ref: 'end', d: 12 } } };
            // The third reply was pinned in empty space: no selector, only
            // fallback coordinates. It must still get a tile.
            const freeAnchor = { fallback: { docX: 1935, docY: 450, viewportW: 1280, docW: 1280 }, viewportW: 1280 };
            const { error: replyError } = await supabaseAdmin.from('feedback_replies').insert([
                { feedback_id: fb.id, content: 'plain reply', author_role: 'client', author_name: seed.clientEmail, created_at: '2026-09-14T10:00:00Z' },
                { feedback_id: fb.id, content: 'same here', author_role: 'client', author_name: seed.clientEmail, created_at: '2026-09-14T10:01:00Z', metadata: { anchor, page_key: 'https://example.com/pricing' } },
                { feedback_id: fb.id, content: 'and in the gap', author_role: 'client', author_name: seed.clientEmail, created_at: '2026-09-14T10:02:00Z', metadata: { anchor: freeAnchor, page_key: 'https://example.com/' } },
            ]);
            if (replyError) throw new Error(`reply insert failed: ${replyError.message}`);

            await page.goto(`/dashboard/feedback/${fb.id}`);
            const tile = page.getByText('Reply pin a', { exact: false });
            await expect(tile).toBeVisible({ timeout: 10_000 });
            // Selector, offset phrasing, and the page it was left on (which
            // differs from the parent's) all come through.
            await expect(page.getByText('#pricing-cta')).toBeVisible();
            await expect(page.getByText('12px below')).toBeVisible();
            await expect(page.getByText('on /pricing')).toBeVisible();
            // Only the anchored replies get a tile, lettered by age.
            await expect(page.getByText('Reply pin b', { exact: false })).toBeVisible();
            await expect(page.getByText('Free position on the page')).toBeVisible();
            await expect(page.getByText('Reply pin', { exact: false })).toHaveCount(2);
        } finally {
            await supabaseAdmin.from('feedback_replies').delete().eq('feedback_id', fb.id);
            await supabaseAdmin.from('feedbacks').delete().eq('id', fb.id);
        }
    });
});
